version: "3"
services:
  api:
    image : crtagadiya/fastapi
    depends_on:
      - postgres
    ports: 
        # - <port on localhost>:<port on container>
        - 80:8000
    volumes:
      - ./:/usr/src/app:ro
    # override docker command from Dockerfile
    command: 
      - alembic upgrade head
      - uvicorn app.main:app --host 0.0.0.0 --port 8000

    # env_file:
    #   - ./.env
    environment:
      - PG_DATABASE_HOST=${PG_DATABASE_HOST}
      - PG_DATABASE_PORT=${PG_DATABASE_PORT}
      - PG_DATABASE_PASSWORD=${PG_DATABASE_PASSWORD}
      - PG_DATABASE_USERNAME=${PG_DATABASE_USERNAME}
      - PG_DATABASE_NAME=${PG_DATABASE_NAME}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_ALGORITHM=${JWT_ALGORITHM}
      - JWT_TOKEN_EXPIRED_MINUTES=${JWT_TOKEN_EXPIRED_MINUTES}

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=fastapi
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:


